// Copy of the backend's src/common/errors/error-code.ts (API contract §8).
// Keep both in sync: pages switch on these codes, never on messages.
export const ErrorCode = {
  // Generic, used when no domain code applies (one per HTTP status).
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  HTTP_ERROR: 'HTTP_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Domain codes from the API contract.
  INVALID_FILE: 'INVALID_FILE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  INVALID_PHOTO_KEY: 'INVALID_PHOTO_KEY',
  NOT_LISTING_OWNER: 'NOT_LISTING_OWNER',
  LISTING_NOT_EDITABLE: 'LISTING_NOT_EDITABLE',
  PICKUP_OPTION_NOT_FOUND: 'PICKUP_OPTION_NOT_FOUND',
  PICKUP_OPTION_LIMIT: 'PICKUP_OPTION_LIMIT',
  LAST_PICKUP_OPTION: 'LAST_PICKUP_OPTION',
  CANNOT_RESERVE_OWN_LISTING: 'CANNOT_RESERVE_OWN_LISTING',
  INVALID_PICKUP_OPTION: 'INVALID_PICKUP_OPTION',
  LISTING_NOT_AVAILABLE: 'LISTING_NOT_AVAILABLE',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  NOT_RESERVATION_SELLER: 'NOT_RESERVATION_SELLER',
  NOT_RESERVATION_BUYER: 'NOT_RESERVATION_BUYER',
  HANDOVER_ALREADY_CONFIRMED: 'HANDOVER_ALREADY_CONFIRMED',
  RECEPTION_ALREADY_CONFIRMED: 'RECEPTION_ALREADY_CONFIRMED',
  RECEPTION_NOT_CONFIRMED: 'RECEPTION_NOT_CONFIRMED',
  ALREADY_RATED: 'ALREADY_RATED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
